[project]
name = "sros_upgrade"
version = "0.2"
requires-python = ">=3.8"

dependencies = [
  "netmiko",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
sros_upgrader = "sros_upgrade.main:main"
